extraction:
  cpp:
    after_prepare: 
      - python report.py 28
  cobol:
    after_prepare: 
      - python report.py 28
  csharp:
    after_prepare: 
      - python report.py 28
  java:
    after_prepare: 
      - python report.py 28
  javascript:
    after_prepare: 
      - python report.py 28
  python:
    after_prepare: 
      - python report.py 28
